export const CHECKLIST_TITLES = {
  NEWSLETTER_TRANSLATIONS: 'Newsletter Translations',
  NEWSLETTER_TESTING_APPROVED: 'Newsletter Testing approved',
  NEWSLETTER_TESTING_APPROVED_GROUP_A: 'Newsletter Testing approved group A',
  NEWSLETTER_TESTING_APPROVED_GROUP_B: 'Newsletter Testing approved group B',
  LPS_APPROVED: 'LPs approved',
  SENT_NSLT_LP_FOR_TESTING: 'Sent NSLT/LP for testing',
} as const;

export const CHECKLIST_TITLES_NORM = {
  NEWSLETTER_TRANSLATIONS: CHECKLIST_TITLES.NEWSLETTER_TRANSLATIONS.toLowerCase(),
  NEWSLETTER_TESTING_APPROVED: CHECKLIST_TITLES.NEWSLETTER_TESTING_APPROVED.toLowerCase(),
  NEWSLETTER_TESTING_APPROVED_GROUP_A: CHECKLIST_TITLES.NEWSLETTER_TESTING_APPROVED_GROUP_A.toLowerCase(),
  NEWSLETTER_TESTING_APPROVED_GROUP_B: CHECKLIST_TITLES.NEWSLETTER_TESTING_APPROVED_GROUP_B.toLowerCase(),
  LPS_APPROVED: CHECKLIST_TITLES.LPS_APPROVED.toLowerCase(),
  SENT_NSLT_LP_FOR_TESTING: CHECKLIST_TITLES.SENT_NSLT_LP_FOR_TESTING.toLowerCase(),
} as const;
